apiVersion: v1
kind: Service
metadata:
  name: lb-javadb
spec:
  type: LoadBalancer
  externalIPs:
  - 18.228.226.210
  - 18.229.132.59
  - 52.67.216.31
  ports:
    - port: 30000
      targetPort: 8081
  selector:
    app: pod-javadb