- hosts:
  - ec2-k8s-m1
  become: yes
  tasks:    
    - name: "Reset cluster"
      shell: "kubeadm reset -f"
      
    - shell: "kubeadm init --control-plane-endpoint 'k8s-haproxy:6443' --upload-certs"
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "

    - name: "Colocando no path da maquina o conf do kubernetes"
      shell: "mkdir -p $HOME/.kube && sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config && export KUBECONFIG=/etc/kubernetes/admin.conf"